// Mapping camelCase (frontend / TypeScript) <-> snake_case (PostgreSQL / Supabase)

export function toRow(d: any) {
  return {
    id:                           d.id,
    statut:                       d.statut,
    raison_sociale:               d.raisonSociale,
    forme_juridique:              d.formeJuridique,
    siret:                        d.siret,
    rcs_ville:                    d.rcsVille,
    activite:                     d.activite,
    description_activite:         d.descriptionActivite,
    nom_gerant:                   d.nomGerant,
    prenom_gerant:                d.prenomGerant,
    nationalite_gerant:           d.nationaliteGerant,
    pays_origine:                 d.paysOrigine,
    tel:                          d.tel,
    email:                        d.email,
    adresse_domicile:             d.adresseDomicile,
    date_debut:                   d.dateDebut,
    date_fin:                     d.dateFin ?? null,
    motif_resiliation:            d.motifResiliation ?? null,
    origine_fonds:                d.origineFonds,
    beneficiaires_declares:       d.beneficiairesDeclares,
    utilisation_adresse:          d.utilisationAdresse,
    est_ppe:                      d.estPPE,
    appartenance_politique:       d.appartenancePolitiqueReligieuse,
    commentaires_controles:       d.commentairesControlesInitiaux,
    niveau_risque_ia:             d.niveauRisqueIA,
    decision_risque_ia:           d.decisionRisqueIA,
    commentaire_risque_ia:        d.commentaireRisqueIA,
    statut_maj_annuelle:          d.statutMiseAJourAnnuelle,
    derniere_maj_annuelle:        d.derniereMajAnnuelle,
    dernier_controle_trimestriel: d.dernierControleTrimestriel,
    statut_conformite_trim:       d.statutConformiteTrimestrielle,
    tarif_choisi:                 d.tarifChoisi,
    montant_mensuel:              d.montantMensuel,
    option_courrier:              d.optionCourrier,
    numero_bal:                   d.numeroBal,
    a_inclure_prochaine_liste:    d.aInclureProchaineListe,
    source_onboarding:            d.sourceOnboarding ?? false,
    docs:                         d.docs,
    relances:                     d.relances,
    paiements:                    d.paiements,
    historique:                   d.historique,
  };
}

export function fromRow(r: any) {
  return {
    id:                              r.id,
    createdAt:                       r.created_at,
    statut:                          r.statut,
    raisonSociale:                   r.raison_sociale,
    formeJuridique:                  r.forme_juridique,
    siret:                           r.siret,
    rcsVille:                        r.rcs_ville,
    activite:                        r.activite,
    descriptionActivite:             r.description_activite,
    nomGerant:                       r.nom_gerant,
    prenomGerant:                    r.prenom_gerant,
    nationaliteGerant:               r.nationalite_gerant,
    paysOrigine:                     r.pays_origine,
    tel:                             r.tel,
    email:                           r.email,
    adresseDomicile:                 r.adresse_domicile,
    dateDebut:                       r.date_debut,
    dateFin:                         r.date_fin,
    motifResiliation:                r.motif_resiliation,
    origineFonds:                    r.origine_fonds,
    beneficiairesDeclares:           r.beneficiaires_declares,
    utilisationAdresse:              r.utilisation_adresse,
    estPPE:                          r.est_ppe,
    appartenancePolitiqueReligieuse: r.appartenance_politique,
    commentairesControlesInitiaux:   r.commentaires_controles,
    niveauRisqueIA:                  r.niveau_risque_ia,
    decisionRisqueIA:                r.decision_risque_ia,
    commentaireRisqueIA:             r.commentaire_risque_ia,
    statutMiseAJourAnnuelle:         r.statut_maj_annuelle,
    derniereMajAnnuelle:             r.derniere_maj_annuelle,
    dernierControleTrimestriel:      r.dernier_controle_trimestriel,
    statutConformiteTrimestrielle:   r.statut_conformite_trim,
    tarifChoisi:                     r.tarif_choisi,
    montantMensuel:                  r.montant_mensuel,
    optionCourrier:                  r.option_courrier,
    numeroBal:                       r.numero_bal,
    aInclureProchaineListe:          r.a_inclure_prochaine_liste,
    docs:                            r.docs,
    relances:                        r.relances,
    paiements:                       r.paiements,
    historique:                      r.historique,
  };
}
